name: Integration Tests (adapted from action found at https://medium.com/flutter-community/run-flutter-driver-tests-on-github-actions-13c639c7e4ab)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  drive:
    # Creates a build matrix for your jobs. You can define different
    # variations of an environment to run each job in.
    strategy:
      # A set of different configurations of the virtual
      # environment.
      matrix:
        device:
        - "iPhone 8 (13.1)"
        - "iPhone 11 Pro Max (13.1)"
      fail-fast: false
    # The type of machine to run the job on.
    runs-on: macos-latest
    # Contains a sequence of tasks.
    steps:
    - name: "List all simulators"
      run: "xcrun instruments -s"
    - name: "Start Simulator"
      run: |
        UDID=$(
          xcrun instruments -s |
          awk \
            -F ' *[][]' \
            -v 'device=${{ matrix.device }}' \
            '$1 == device { print $2 }'
        )
        xcrun simctl boot "${UDID:?No Simulator with this name found}"
    - uses: actions/checkout@v1
    # Sets up a flutter environment.
    # https://github.com/marketplace/actions/flutter-action
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'dev' or 'beta'
    - name: "Run Flutter Driver tests"
      run: "flutter drive ---driver=test_driver/integration_test.dart --target=integration_test/login_test.dart"
